// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3.0
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x2000 ~
// 0x3fff : Memory 'data_V' (1024 * 64b)
//          Word 2n   : bit [31:0] - data_V[n][31: 0]
//          Word 2n+1 : bit [31:0] - data_V[n][63:32]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XPACKETGENERATOR_PACKETGENERATOR_AXILITES_ADDR_DATA_V_BASE 0x2000
#define XPACKETGENERATOR_PACKETGENERATOR_AXILITES_ADDR_DATA_V_HIGH 0x3fff
#define XPACKETGENERATOR_PACKETGENERATOR_AXILITES_WIDTH_DATA_V     64
#define XPACKETGENERATOR_PACKETGENERATOR_AXILITES_DEPTH_DATA_V     1024

