// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3.0
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPACKETGENERATOR_PACKETGENERATOR_H
#define XPACKETGENERATOR_PACKETGENERATOR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpacketgenerator_packetgenerator_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XPacketgenerator_packetgenerator_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XPacketgenerator_packetgenerator;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPacketgenerator_packetgenerator_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPacketgenerator_packetgenerator_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPacketgenerator_packetgenerator_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPacketgenerator_packetgenerator_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPacketgenerator_packetgenerator_Initialize(XPacketgenerator_packetgenerator *InstancePtr, u16 DeviceId);
XPacketgenerator_packetgenerator_Config* XPacketgenerator_packetgenerator_LookupConfig(u16 DeviceId);
int XPacketgenerator_packetgenerator_CfgInitialize(XPacketgenerator_packetgenerator *InstancePtr, XPacketgenerator_packetgenerator_Config *ConfigPtr);
#else
int XPacketgenerator_packetgenerator_Initialize(XPacketgenerator_packetgenerator *InstancePtr, const char* InstanceName);
int XPacketgenerator_packetgenerator_Release(XPacketgenerator_packetgenerator *InstancePtr);
#endif


u32 XPacketgenerator_packetgenerator_Get_data_V_BaseAddress(XPacketgenerator_packetgenerator *InstancePtr);
u32 XPacketgenerator_packetgenerator_Get_data_V_HighAddress(XPacketgenerator_packetgenerator *InstancePtr);
u32 XPacketgenerator_packetgenerator_Get_data_V_TotalBytes(XPacketgenerator_packetgenerator *InstancePtr);
u32 XPacketgenerator_packetgenerator_Get_data_V_BitWidth(XPacketgenerator_packetgenerator *InstancePtr);
u32 XPacketgenerator_packetgenerator_Get_data_V_Depth(XPacketgenerator_packetgenerator *InstancePtr);
u32 XPacketgenerator_packetgenerator_Write_data_V_Words(XPacketgenerator_packetgenerator *InstancePtr, int offset, int *data, int length);
u32 XPacketgenerator_packetgenerator_Read_data_V_Words(XPacketgenerator_packetgenerator *InstancePtr, int offset, int *data, int length);
u32 XPacketgenerator_packetgenerator_Write_data_V_Bytes(XPacketgenerator_packetgenerator *InstancePtr, int offset, char *data, int length);
u32 XPacketgenerator_packetgenerator_Read_data_V_Bytes(XPacketgenerator_packetgenerator *InstancePtr, int offset, char *data, int length);

#ifdef __cplusplus
}
#endif

#endif
